name: vampy

channels:
  - conda-forge

dependencies:
  - fenics
  - morphman
  - paramiko
  - pip
  - git
  - python >=3.8
  - expat==2.5 # Hotfix for https://gitlab.archlinux.org/archlinux/packaging/packages/paraview/-/issues/4
  - pip:
      - scipy
      - cppimport
      - git+https://github.com/mikaem/Oasis
