name: vampy

channels:
  - conda-forge

dependencies:
  - fenics
  - morphman
  - paramiko
  - pip
  - python ==3.8.15
  - git
  - vtk <= 9.1.0
  - numpy <= 1.24.4
  - pip:
      - matplotlib
      - scipy
      - cppimport==22.8.2
      - git+https://github.com/KVSlab/OasisMove
