name: vampy

channels:
  - conda-forge

dependencies:
  - fenics
  - morphman
  - paramiko
  - pip
  - python <=3.10
  - git
  - vtk <= 9.1
  - numpy <= 1.24.4
  - pip:
      - scipy
      - cppimport
      - git+https://github.com/KVSlab/OasisMove
