name: vampy

channels:
  - conda-forge

dependencies:
  - fenics
  - morphman
  - paramiko
  - pip
  - python >=3.8
  - git
  - matplotlib
  - pytest
  - pytest-cov
  - pip:
      - cppimport
      - git+https://github.com/mikaem/Oasis
