name: Test package

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - refactor-vampy
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - refactor-vampy

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"


jobs:
  #  check-code:
  #    runs-on: ubuntu-22.04
  #    container: hkjeldsberg/vampy:latest
  #
  #    steps:
  #      # This action sets the current path to the root of your github repo
  #      - uses: actions/checkout@v3
  #
  #      - name: Upgrade pip and setuptools
  #        run: python3 -m pip install pip setuptools --upgrade
  #
  #      - name: Install types-paramiko
  #        run: python3 -m pip install types-paramiko
  #
  #      - name: Install code
  #        run: python3 -m pip install .[test]
  #
  #      - name: Flake8 code
  #        run: python3 -m flake8

  #      - name: mypy code
  #        run: python3 -m mypy --exclude Probe.py

  test-code:
    # This code depends on the result of check-code
    #    needs: check-code
    runs-on: ubuntu-latest
    # container: quay.io/fenicsproject/stable:latest
    #    container: finsberg/fenics-extra
    #container: hkjeldsberg/vampy:latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

